name: The Grid Tester
favicon: null
layout_spectrum: 0.21959694474935532
typography_spectrum: 0.2135979316662997
title: Just Testing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.13371502375230193
  lightness: 0.899980062386021
  saturation: 0.6516239100601524
  rhythmicContrast: 0.799843902233988
purpose: []
